### ISSUE TITLE
memory leak in audio_capture  (ros ticket #17)

### ISSUE THREAD

**Issue by ahendrix** [ros-drivers/audio_common#17] opened 2013-03-14 22:58 UTC
I found a memory leak when not unrefing the buffer in the onNewBuffer() callback

attached is a patch

trac data:
 * Owner: **ahendrix**
 * Reporter: **mikebosse**
 * Reported at: **Mon Oct 29 20:27:34 2012**
 * URL: https://kforge.ros.org/audiocommon/trac//ticket/17

**Comment by trainman419** [comment] 2015-08-28 16:59
Duplicate of #18.

**Closed by trainman419** 2015-08-28 16:59 UTC
Labels: bug, major
