### ISSUE TITLE
rosdep install audio_common does not resolve issues for rosdep install audio_capture, etc

### ISSUE THREAD

**Issue by compiaffe** [ros-drivers/audio_common#44] opened 2015-07-21 09:56 UTC
On a Ubuntu 15.05 64-bit system running ROS Jade:

After following the tutorial here: http://wiki.ros.org/audio_common/Tutorials/Streaming%20audio 
and installing from source audio_capture had an unmet dependency on gstreamer-0.10.
##rosdep install audio_common## reported everything being installed.

However, audio_capture still had the missing dependency. Finally 
##rosdep install audio_capture## solved the issue.

Shouldn't this already happen on rosdep install audio_common?

**Comment by jack-oquin** [comment] 2015-07-21 22:10
I assume you mean 15.04, Vivid Vervet.

If you are using rosdep to resolve the dependencies, why not just install those Ubuntu packages directly?
```
sudo apt-get install ros-jade-audio-capture
```

**Comment by compiaffe** [comment] 2015-07-22 07:19
Sure, I meant 15.04.

I am modifying the source to allow for changing the topic to listen on/publish as as well as starting and stopping the audio play. (Audio_play had the same dependencies issue)

Maybe my understanding of the metapackage functionality is wrong: I thought it allows for installing or resolving of dependencies for all subpackages.

**Comment by jack-oquin** [comment] 2015-07-22 22:22
A metapackage (or any package, really) declares all its direct dependencies, allowing rosdep to install all its direct and indirect dependencies.

Exactly what dependency was installed by audio_capture, but not audio_common?

**Comment by compiaffe** [comment] 2015-07-24 14:46
I'm unsure which exact dependencies were missing... I will have to try this on a vanilla install some time next week.
Top of my head I am certain about the gstreamer-0.10 package. I'll let you know.

**Comment by jack-oquin** [comment] 2015-07-24 16:28
If you believe there is a bug, and want someone to actually change the code, please add a detailed description of how to demonstrate the error.

**Comment by trainman419** [comment] 2015-08-28 16:41
Closing because I cannot reproduce.

**Closed by trainman419** 2015-08-28 16:41 UTC
