### ISSUE TITLE
Sound_play should co-exist with non-ROS applications  (ros ticket #8)

### ISSUE THREAD

**Issue by ahendrix** [ros-drivers/audio_common#8] opened 2013-03-14 22:58 UTC
sound_play seems to occupy audio device files, preventing non-ROS
 applications from using sound. Many users have non-ROS applications, like
 screen readers for the blind, which need to run.

trac data:
 * Owner: **ahendrix**
 * Reporter: **paepcke**
 * Reported at: **Fri Sep  7 14:33:24 2012**
 * URL: https://kforge.ros.org/audiocommon/trac//ticket/8

**Comment by trainman419** [comment] 2015-08-28 16:49
Closing because I could not reproduce this when it was filed, and I still cannot reproduce this on 14.04.

**Closed by trainman419** 2015-08-28 16:49 UTC
Labels: bug, major
